apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-poller
  namespace: default
  labels:
    app: ping-poller
spec:
  selector:
    matchLabels:
      app: ping-poller
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ping-poller
    spec:
      containers:
      - name: ping-poller
        image: raguyazhin/ping-poller-api:7.0.0
        securityContext:
          capabilities:
            add:
            - NET_RAW
            drop:
            - ALL
